common: &common
  adapter: postgresql
  username: seanwalker
  host: localhost

development:
  <<: *common
  database: dayable_development

test:
  <<: *common
  database: dayable_test

production:
  <<: *common
  database: dayable_production